site_name: Sentinel‑1 Batch Pipeline
site_url: https://mariskalinka.github.io/s1_batch_snap/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - toc.integrate

nav:
  - Overview: index.md
  - Pipeline:
      - Diagram: diagrams/pipeline.md
      - Makeflow: diagrams/makeflow.md
  - Usage:
      - Download SAFE: usage/download.md
      - Processing: usage/process.md
      - COG & STAC: usage/cog_stac.md
  - Notebooks: notebooks.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - def_list

extra:
  generator: false